global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cassandra"
    static_configs:
      - targets:
          - "cassandra-node1:8080"
          - "cassandra-node2:8080"
    metrics_path: "/metrics"
    scheme: "http"
